Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/*_spec.rb'

# Rubocop 0.56 causes false positives
# https://github.com/bbatsov/rubocop/issues/5887
Lint/SplatKeywordArguments:
  Enabled: false
