%YAML 1.1
---
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/*_spec.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
...
